### ISSUE TITLE
It doesn't work with SSR

### ISSUE THREAD

**Issue by mihirsoni** [reactotron/reactotron#129]
Hi, 
Thanks for the wonderful too. It seems it doesn't work with SSR or am I doing something worng ?

I am getting  following error.

```js
node_modules/reactotron/dist/client.js:16:6
```

**Comment by mihirsoni** [comment]
Okay , I am able to make it work with using `__SERVER__` Flag form webpack saying that , require in store only if it is client.

```js
const middlewares = [];
if (!__SERVER__) {
      const Reactotron = require('reactotron'); // eslint-disable-line global-require
      middlewares.push(Reactotron.reduxMiddleware);
}
```

**Comment by skellock** [comment]
Thanks.  Do you know if there's a bootstrap repo out there where I could try using this?  I've never created an isomorphic type app.  :)

**Comment by mihirsoni** [comment]
@skellock I will try to push the bootstrap repo or you can try the same with [this boilerplate](https://github.com/erikras/react-redux-universal-hot-example). So basically you have to make sure you add middleware only on client. 

I have added that on document with PR, that worked for me and seems the actual solution.

Let me know if you need more information.

Thanks for the great tool.

**Comment by skellock** [comment]
Getting ready to prep a 1.0 launch here, and I probably murdered your PR.  Rebasing won't really make sense at this point as it's entirely a new code base.

You're welcome to do another PR, by all means though!  Just know that i pulled the rug out from underneath you.  =)

Shortly (next week?) I'm going to look into SSR and I'll give you the proper credit when I make any changes.

Thanks for putting this on my radar!
