### ISSUE TITLE
How to connect to Reactotron from Android Phone?

### ISSUE THREAD

**Issue by justingosan** [reactotron/reactotron#162]
I tried:
```
Reactotron.configure() // we can use plugins here -- more on this later
  .connect({
  enabled: true,
  host: '192.168.1.200',  // server ip
  port: 9090
})
```

PS: Reactotron works on iPhone and Android emulator

**Comment by skellock** [comment]
Try forwarding that port with adb.

`adb reverse tcp:9090 tcp:9090`

**Comment by justingosan** [comment]
Still doesnt seem to work :(

**Comment by skellock** [comment]
Even with your host left to localhost and that adb port forward?  Thats odd.  Will take a look first thing in the AM.  You will have justice!

**Comment by skellock** [comment]
Btw, that line should read `Reactotron.configure().connect()`.  The only thing you might need is `configure({host: '192.168.1.200'})` but thats only if you arent tethered. The port is default and enabled isnt a thing anymore. :)

**Comment by justingosan** [comment]
Ah yes that was a typo on my part here. :)

I tried `Reactotron.configure().connect()` while tethered and with the adb port forward and also with `.configure({host: '192.168.1.200'})` while using adb connect via wifi just now. Both times still wouldn't connect to the desktop  or cli client from the phone :(

Is there any way I can turn on Reactotron debug logs so I can provide more info?

**Comment by skellock** [comment]
Under `node_modules/reactotron-core-client/dist/index.js` in your project directory, you'll find your the connection code. You can hack around in there.

Is the new Reactotron running?  The old one was on a different port fwiw.  

Are you able to connect fine from an android emulator?  Are you on Windows?

**Comment by skellock** [comment]
Alright, I tested again here, and I'm having problems reproducing.  Here's my setup:

Mac OS X.  Latest Reactotron.app launched.  Android 6.x on a Nexus 7 (2013).  Tethered and on local wifi.  I'm no configuration options (so just the defaults).  And I had to `adb reverse tcp:9090 tcp:9090` to open up.

No problems.

What kind of setup do you have there?

**Comment by justingosan** [comment]
I'll have my reply up first thing tomorrow morning! Give or take in the
next 12 hours 😄 thanks for all your help so far!

**Comment by justingosan** [comment]
Okay so I moved my workspace to my Macbook and everything seems to be working fine (even specifying `host`). Not so sure what's up with my iMac but I will investigate for a fix. Thanks again for your help!

**Comment by xemasiv** [comment]
can confirm

run `adb reverse tcp:9090 tcp:9090` to forward port
run `adb reverse --list` to ensure it's there

add the ff code (if tethering, you can also use an specific IP address)

```
  Reactotron
    .configure({
      host: 'localhost' // added code
    })
    // ...
    .connect()
```

**Comment by MiltonBO** [comment]
I am using the Android Emulator and I had to configure Proxy settings in my emulator to access my local server, now I put the same IP address to configure and now it is working.

import Reactotron from 'reactotron-react-native'

```
Reactotron
.configure({
    host: '10.0.2.2'
}) // controls connection & communication settings
.useReactNative() // add all built-in react native plugins
.connect()
```

**Comment by notmarinho** [comment]
@miltonbo worked for me on android but stoped on android. To fix, only do this logic:
```
Reactotron
  .configure({
    host:  Platform.OS === 'android' ? '10.0.2.2' : 'localhost',
  })
```

**Comment by WayneKim92** [comment]
If you are inconvenient to manually enter the IP when connecting reactotron to the actual device, try using this [plugin](https://github.com/WayneKim92/babel-plugin-local-ip).
