### ISSUE TITLE
Register Reactotron in homebrew cask tap - make it installable using brew cask install

### ISSUE THREAD

**Issue by jsynowiec** [reactotron/reactotron#163]
Register a new Cask for Reactotron in [Homebrew Cask](https://github.com/caskroom/homebrew-cask). This will allow to install Reactotron OS X application using `brew cask install reactotron` command.

**Comment by skellock** [comment]
Sure!  Thanks for the heads up.

**Comment by jsynowiec** [comment]
I've created a pull request to homebrew-cask: https://github.com/caskroom/homebrew-cask/pull/24012

**Comment by skellock** [comment]
Oh Thanks.  Lemme know if theres anything I need to do.

**Comment by jsynowiec** [comment]
To make it easier to maintain, each future GitHub release should have the `Reactotron.app.zip` archive attached. Right now, the 1.0.1 is cli-only, so I've registered version 1.0.0 in the Cask.

If there is an archive in every release we can use the [appcast](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md) stanza which provides information on future updates.

**Comment by skellock** [comment]
Gotcha, ya I opted for a monorepo with a shared version number.  Which means, some components will be skipping version numbers but its still all semver.

It'd be cool if there were an alternate way to flag updates to cask other than gh releases.

I'll keep this issue open and investigate further.  I've never used cask.  Looks great!

**Comment by skellock** [comment]
Oh, their shortcat example shows that this is possible!  Neato mosquito.

**Comment by jsynowiec** [comment]
#164

**Comment by jsynowiec** [comment]
@skellock  my PR to homebrew-cask is now closed. I've added the appcast to the Cask. One of the maintainers clarified that it's not used in the way I thought it is right now.

For future version releases (and updates in the relevant Cask) you can open an issue and assign me to it.

**Comment by skellock** [comment]
Thanks.  You want me to create that appcast release.atom file?

**Comment by jsynowiec** [comment]
Its not necessary. This feed is automatically updated by GitHub.

**Comment by skellock** [comment]
You're awesome.  Thank you.
