### ISSUE TITLE
Add button to clear event timeline

### ISSUE THREAD

**Issue by lucasbento** [reactotron/reactotron#167]

**Comment by skellock** [comment]
Good point.  Command-K is the keyboard shortcut until then.

**Comment by lucasbento** [comment]
@skellock we should document that somewhere.

**Comment by skellock** [comment]
Click Help in the bottom left and scroll down to the keyboard section.

![image](https://cloud.githubusercontent.com/assets/68273/17937872/9f5d0ae2-69f1-11e6-9244-bbbfafdc572a.png)

Point taken though.  Help could be better.  :)

**Comment by lucasbento** [comment]
@skellock oh, cool! :)

**Comment by Thorbenandresen** [comment]
Is there a Reactotron.clear() statement by any chance or something else I could put in the ComponentDidMount of my root component to clear upon reload?

**Comment by oldo** [comment]
@Thorbenandresen see issue #220 
Apparently this has been implemented in version 1.3

**Comment by skellock** [comment]
Oops.  Yes.  Good to go.
