### ISSUE TITLE
nonthing found in the app

### ISSUE THREAD

**Issue by hainuo** [reactotron/reactotron#171]
![qq20160825-0](https://cloud.githubusercontent.com/assets/421861/17959126/e78c93de-6ad0-11e6-9ea3-785a474485db.png)

i got  view like this pic on  macosx 10.11.6 and  app version 1.0.0

how can i  use it?

**Comment by skellock** [comment]
Woah.  Thats not right!  Haha.

Is there a chance that youre running something else on port 9090?  Maybe the cli version?

I'll put a better error message in rather than this snowstorm effect.

**Comment by hainuo** [comment]
i  run it well  when i  compile the app from sourcecode. 
now  i use the version compiled for source code
thank for your help, but  i  don't know which app or someelse thinings use the port 9090  becasue i like the port 80 for my local project of php

**Comment by skellock** [comment]
Is your file system formatted with case-sensitivity turned on by chance?

**Comment by hainuo** [comment]
@skellock   yes, it is!

**Comment by skellock** [comment]
https://github.com/reactotron/reactotron/pull/170 has the fix incoming.  Sorry about that.

**Comment by hainuo** [comment]
thanks
