### ISSUE TITLE
Reactotron connection over Wi-Fi

### ISSUE THREAD

**Issue by Mastergalen** [reactotron/reactotron#172]
Does Reactotron support connecting over Wi-Fi?

I've set the Debug server host in Dev Settings to the local IP of my Mac `10.61.180.184:8081`.

I also tried to force Reactotron to manually connect to the local IP:

```javascript
Reactotron
  .configure() // we can use plugins here
  .use(trackGlobalErrors())
  .connect({host: '10.61.180.184'});
```

However, when I open the CLI or the app I don't receive a **Connection** event after I reload the app.

**Comment by skellock** [comment]
The configuration should be in the configure function.  Try moving it up from connect.

**Comment by Mastergalen** [comment]
```javascript
Reactotron
  .configure({host: '10.61.180.184'}) // we can use plugins here
  .use(trackGlobalErrors())
  .connect();
```

Oh, yep - that was it, thanks :)

I guess there is no easy way to fetch the dev server host set in the dev settings debugger menu?

**Comment by skellock** [comment]
I'm not sure.  I didn't know that was a thing.  I'll look around and see what's up.  Thanks for the suggestion.
