### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by avishayil** [reactotron/reactotron#174]
Does reactotron supports debugging on Android?

**Comment by skellock** [comment]
Yep!  Don't for get to `adb reverse tcp:9090 tcp:9090` to tunnel back to the mothership.

**Comment by avishayil** [comment]
Thanks!

**Comment by skellock** [comment]
I'll update the docs to be clear about this step.

**Comment by FireQQTW** [comment]
I use Genymotion(Version: 2.7.2) run emulator(Samsung Galaxy S6),  and run `reverse tcp:9090 tcp:9090`, but still can't connect :(

Any other suggest? Thx.

**Comment by skellock** [comment]
Is Reactotron running?  Are you on a Mac?  Does your S6 image run Android 5.x+?

**Comment by FireQQTW** [comment]
Sorry, I did not provide enough information.
Yes, I try to open cmd and APP, but still can't connect.

OS: OS X
Android version: 6.0

**Comment by skellock** [comment]
How are you connecting to Reactotron?

`Reactotron.configure().connect()` should be fine.

Also, check your emulator config in Genymotion.  Are you in NAT mode?

![image](https://cloud.githubusercontent.com/assets/68273/17974425/074aa7aa-6ab4-11e6-8691-3f5738a75d88.png)

No firewalls running on your computer or shenanigans like that?

Another option is to try `Reactotron.configure({ host: '10.0.3.2' }).connect()`  as that's Genymotion's default to get back to the host machine.  This bypasses the need to do a reverse portforward with ADB.

**Comment by FireQQTW** [comment]
I try this project demo [(link)](https://github.com/reactotron/reactotron/blob/master/packages/demo-react-native/App/Config/ReactotronConfig.js), or `Reactotron.configure().connect()`, 
My mdoe is NAT, and try to added `host: '10.0.3.2'`, but still the same.

I need close `http://localhost:8081/debugger-ui`?  or disable live reload and hot reloading?

**Comment by skellock** [comment]
Hot reloading is fine.

![image](https://cloud.githubusercontent.com/assets/68273/17975713/c1334a42-6ab8-11e6-9bae-e1498f786081.png)

But it does look like Remote JS Debugging hijacks the websocket communication channel!

Can you confirm by turning that off?

![image](https://cloud.githubusercontent.com/assets/68273/17975821/2d6c91aa-6ab9-11e6-9174-1133e97c4fa1.png)

**Comment by FireQQTW** [comment]
Fix!!!

I stop "Debug JS Remotely", and it's work!!!

Thanks!!!!! :)

**Comment by skellock** [comment]
Added these notes to the README.  Thank you @FireQQTW and @avishayil for filing these issues!

**Comment by skellock** [comment]
Oh good!  Thanks @zalmoxisus .  Man you're on top of *everything*!

**Comment by zalmoxisus** [comment]
Should work on `react-native@0.32.0`: https://github.com/facebook/react-native/issues/9523#issuecomment-244413771

**Comment by skellock** [comment]
I feel like I owe you several beers @zalmoxisus .
