### ISSUE TITLE
Issues with Reactotron application

### ISSUE THREAD

**Issue by pgom** [reactotron/reactotron#178]
I'm having trouble working the application. While I can connect with my application with Reactotron in terminal, on the App nothing happens. Is there any extra configuration needed?

**Comment by pgom** [comment]
I was too fast opening this issue. Found the answer to my problem [here.](https://github.com/reactotron/reactotron/blob/master/docs/troubleshooting.md#turn-off-remote-js-debugging)

**Comment by skellock** [comment]
Good stuff. Always appreciate people reporting issues.
