### ISSUE TITLE
Update our cask to 1.1

### ISSUE THREAD

**Issue by skellock** [reactotron/reactotron#184]
Hey @jsynowiec, you asked https://github.com/reactotron/reactotron/issues/163 in here to notify on update.

If you just want to show me this one time how it's done, I could probably handle it going forward?  <3

Binary is: https://github.com/reactotron/reactotron/releases/download/v1.1.0/Reactotron.app.zip

**Comment by jsynowiec** [comment]
@skellock I have a PR ready but waiting for #185 before pushing it.

Updating is easy. You just have to change the version number, update checksums and confirm, that everything installs/uninstalls correctly. It's not a big deal so I can keep that Cask up-to-date if you want. Just ping when planning a release.

**Comment by jsynowiec** [comment]
PR with 1.1.1 update caskroom/homebrew-cask/pull/24085

**Comment by jsynowiec** [comment]
Merged
