### ISSUE TITLE
Wrong version number in the about window

### ISSUE THREAD

**Issue by jsynowiec** [reactotron/reactotron#185]
The 1.1.0 release of OS X application shows wrong version number in the about window.

<img width="396" alt="reactotron-1 1 0-about" src="https://cloud.githubusercontent.com/assets/1029142/18028857/bbb774b8-6c88-11e6-899f-901f4bf1fbda.png">

https://github.com/reactotron/reactotron/releases/download/v1.1.0/Reactotron.app.zip
MD5 (Reactotron.app.zip) = e067f431657dd2fca700cfce9d818a11

**Comment by skellock** [comment]
Crap.  Did I bump bump the version after the build?

**Comment by jsynowiec** [comment]
Don't know if this helps but checksums for 1.0 and 1.1 archives are different ;) I've just rechecked and binary form 1.1 release has '1.0.0' in both, package.json and Info.plis files.

**Comment by skellock** [comment]
Fixes #184 and #185.  

Oops.  😊 

`https://github.com/reactotron/reactotron/releases/download/v1.1.1/Reactotron.app.zip`
