### ISSUE TITLE
i got warn when i use the lastest version of react-native which is 0.32.0

### ISSUE THREAD

**Issue by hainuo** [reactotron/reactotron#189]
npm WARN reactotron-react-native@1.1.0 requires a peer of react-native@^0.31.0 but none was installed.

**Comment by skellock** [comment]
Sorry mate.  All fixed up with `reactotron-react-native 1.1.2`.

**Comment by hainuo** [comment]
so fast!

**Comment by skellock** [comment]
Haha, your issue came while I was in the middle of fixing.  Your timing was perfect, the speed was an illusion!  😆
