### ISSUE TITLE
Reflux instead of Redux

### ISSUE THREAD

**Issue by jonstuebe** [reactotron/reactotron#191]
Hey, are you planning on supporting other flux models? I like redux but don't use it at my work and would love to still be able to use reactotron.

**Comment by skellock** [comment]
Yup, this is very possible.  It does, however, involve writing a plugin that speaks to Flux and provides the information to Reactotron.

**Comment by jonstuebe** [comment]
I would love this. When I have some time I'm going to start working on it.
