### ISSUE TITLE
Apisauce logging url with GET params

### ISSUE THREAD

**Issue by ruskid** [reactotron/reactotron#196]
Using CLI v1.1.2

`api.get('/followers', { username: username })`

The log in CLI appears as **http:host/followers** when **http:host/followers/username=Bob** expected

**Comment by skellock** [comment]
Ahh... Axios uses a separate object called `params` to hold those query string variables.

Looks like we'll need to append them ourselves here:

https://github.com/reactotron/reactotron/blob/master/packages/reactotron-apisauce/src/index.js#L5

**Comment by skellock** [comment]
This is now in place in `1.2`.  Cheers.
