### ISSUE TITLE
Reactotron CLI empty on linux

### ISSUE THREAD

**Issue by Fandekasp** [reactotron/reactotron#197]
Using reactotron-cli@1.1.2 and reactotron-react-native@1.1.2  on Arch Linux.

![screenshot-2016-09-05_15-19-19](https://cloud.githubusercontent.com/assets/260983/18238963/ca1710fe-737c-11e6-964d-43f030f111f2.png)

```
import Reactotron from 'reactotron-react-native';

const options = {
  name: 'My Android App',
  server: '127.0.0.1',
  port: 9090,
};

Reactotron
  .configure() // we can use plugins here -- more on this later
  .connect(options); // let's connect!
```

Any idea how to debug/fix this issue ? Thank you for your support

**Comment by skellock** [comment]
Are you running an emulator?  Did you `adb reverse TCP:9090 TCP:9090` so your emulator can forward 127.0.0.1 to your host machine when this CLI is running?

**Comment by Fandekasp** [comment]
This did the trick! Looking back at the documentation, I can see it was added to the troubleshooting section, sorry for missing it.

Thank you for your help
Cordially
