### ISSUE TITLE
Making Api Responses Selectable

### ISSUE THREAD

**Issue by mustafakosker** [reactotron/reactotron#198]
The response returned from the api is not selectable, it'd be nice if we can select and copy the complete request.

**Comment by skellock** [comment]
Heyo!

You mean the API response?   I like it!

What specifically would you want to copy to the clipboard?   Just the payload?   In JSON format?

**Comment by mustafakosker** [comment]
Exactly! Payload in json format would be nice. It'd be better if we could copy both request and response. I can work on this as well.

**Comment by skellock** [comment]
Copy & paste is now in as of `1.2`.  Cheers!
