### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by jeveloper** [reactotron/reactotron#199]
Hi there

My app is still fairly barebones

Any hints?

ReferenceError: window is not defined
    at Object.<anonymous> (/node_modules/reactotron-react-js/dist/index.js:95:14)
    at Module._compile (module.js:541:32)
    at Module.require._compile (node_modules/gluestick/node_modules/webpack-isomorphic-tools/babel-transpiled-modules/index.js:414:28)
    at Module._extensions..js (module.js:550:10)

**Comment by skellock** [comment]
I see you're using isomorphic... is perhaps this getting loaded on the server, where `window` isn't a thing?

Does this help https://github.com/reactotron/reactotron/issues/129#issuecomment-240091289?

**Comment by jeveloper** [comment]
You're right
i use gluestick with my reactapp and this is happening on node side during transpiling 

i moved this code to componentDidMount 
this way window is present, but nothing seems to happen except an error is gone.

i'm not using barebones reactapp from fb , mine is with reducers, actions and component structure, curious where the right place for reactron to live in :)

thanks

FYI , brew cask had version 1.1.1 only though

**Comment by skellock** [comment]
Hmm.  With isomorphic, does the redux store live client side or server side?

Also, 1.1.1 is the latest release of the app.  I'm opted to use a shared version number (via lernajs) on all the components for this monorepo.

**Comment by jeveloper** [comment]
It should be on client, but i think the process of babel transpiling is messing this up
ill close the ticket :)

thanks !

**Comment by messense** [comment]
This causes some problem when running test cases using serverless Node environment in react-native. Had to do some dirty hack to workaround it:

```javascript
global.window = {
  navigator: {}
};

**Comment by skellock** [comment]
Interesting, perhaps [this is causing a problem](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-react-native/src/index.js#L28)?

**Comment by messense** [comment]
@skellock Yes. But `window` is `undefined` too when running tests in Nodejs using mocha.

`window` is not defined makes it hard to write testable code.

**Comment by skellock** [comment]
Gotcha.  It sounds as if Reactotron shouldn't be loaded during these tests.  That kinda makes sense.  So perhaps ensuring `__DEV__` is set to false during your tests would be an answer?

Lemme know if there's anything you think I can/should do to help.

**Comment by RusAlex** [comment]
Seems reactotron not well encapsulated it's logic. It mustn't mutate `window` global object during importing. 

Thanks

**Comment by skellock** [comment]
Agreed.  I do this because of an issue with ReactNative and Socket.IO.  Socket.IO is hardcoded to look for `window.navigator` before it gets included for the first time.  React Native doesn't have that environment, so I have to enforce that.  :(

I'm going to be replacing the Socket.IO layer in Reactotron in 2.0.  There's been too many issues I've had with it.

**Comment by skellock** [comment]
Good news. Looks like the latest `socket.io` dependency fixed the need to monkeypatch navigator in React Native.

End of an era.

https://github.com/socketio/engine.io-parser/pull/55

**Comment by brendan-rius** [comment]
I am getting the same problem because of https://github.com/infinitered/reactotron/blob/master/packages/reactotron-react-js/src/index.js#L14
