### ISSUE TITLE
RN - nothing in event timeline

### ISSUE THREAD

**Issue by jeveloper** [reactotron/reactotron#204]
Running RN 28
node: 6.x
reactron is totally empty
npm start is running 

followed instructions 

xcode + plugged in device 

thanks

**Comment by skellock** [comment]
By default the Reactotron client tries to connect to localhost on port 9090.   When you're running mobile, this isn't where your Reactotron app lives; it's back on your computer.

So you'll need to specify the IP address of your computer in your `ReactotronConfig.js` file; maybe something like `connect({ host: '10.0.1.1xx' })`.

**Comment by jeveloper** [comment]
Ohh thank you ill try that out

**Comment by skellock** [comment]
Android has a solution for this type of problem with reverse tcp tunnelling, but afaik, we're out of luck on iOS.

**Comment by jeveloper** [comment]
@skellock quick question

changed index.ios.js line 1


Reactotron
  .configure() // we can use plugins here -- more on this later
  .connect({ host: '192.168.2.10', port: 8081 }) // let's connect!

npm start - using 8081 for RN 
does it need to run in debug mode? RN that is
running from xcode in debug mode 

not seeing anything in reactron

**Comment by skellock** [comment]
I'm sorry, it's configure that accepts the host, not connect.  Blah.  Sorry about that.  I used to `connect` pre-1.0.  Then I introduced `configure()` and `connect()` as 2 separate steps.

I'll see what it would take to have `connect()` take these params too.

**Comment by jeveloper** [comment]
thanks that worked :)
