### ISSUE TITLE
Most actions 'undefined'

### ISSUE THREAD

**Issue by mschipperheyn** [reactotron/reactotron#209]
When I use reactotron, many actions are classified as undefined (they aren't). I use immutable.js. Sometimes I dispatch actions that don't mutate state, as a kind of logging mechanism. But many of the actions that contain relevant data and do mutate state, don't show up either. In fact, most of them.
<img width="502" alt="screen shot 2016-09-18 at 21 21 21" src="https://cloud.githubusercontent.com/assets/384959/18620308/dfcfda52-7de5-11e6-89fa-470f2121404e.png">

<img width="569" alt="screen shot 2016-09-18 at 21 19 02" src="https://cloud.githubusercontent.com/assets/384959/18620292/92ccd890-7de5-11e6-89a4-96372ea6f981.png">

**Comment by skellock** [comment]
Immutable.js isn't supported just yet.  PRs accepted!  :)

**Comment by skellock** [comment]
Closing in favour of tracking this feature in #242 .

Appreciate you filing a report here.
