### ISSUE TITLE
Host configuration react native

### ISSUE THREAD

**Issue by fud** [reactotron/reactotron#213]
I can't see where I can configure a host param when working on a device (iOS) on react native. It try's to connect to ws://localhost:9090

For the package server I've set, RCTWebSocketExecutor.m to point to my dev server,

```
#if TARGET_IPHONE_SIMULATOR
    host = @"localhost";
#else
    host = @"10.0.0.29";
#endif
```

I hoped to do something similar with reactotron.

**Comment by skellock** [comment]
Have a look at [react-native-config](https://github.com/luggit/react-native-config).  It is very good for this kind of thing.  Works great on ye olde Android.  Supports multiple .env files.  Configurable with environmental vars when building or Xcode schemes when developing.

**Comment by fud** [comment]
Thanks @skellock that might be exactly what I need. And cheers for the quick response.
