### ISSUE TITLE
Clear timeline on reload

### ISSUE THREAD

**Issue by maluramichael** [reactotron/reactotron#220]
An option which can be enabled by the user that clears the timeline on reload. This is pretty react-native specific. I don't know how react in web handles things like reload. Maybe when the browser reloads the timeline could be cleared.

**Comment by skellock** [comment]
@GantMan has asked for this as well.  Lemme get that feature in.  You're right though, it'll be a signal we'll have to send from the client to the server.  No problem to implement though.

**Comment by maluramichael** [comment]
Ow did not found another issue about this.

**Comment by skellock** [comment]
Thats because I talked to him in person.  Haha.

**Comment by skellock** [comment]
What would you think if we made it "on-demand" and "opt-in".   So, for example, in your startup code, you'd write something like: 

```js
Reactotron.clear()
```

**Comment by maluramichael** [comment]
I'am fine with this 🏆

**Comment by skellock** [comment]
Will roll out today or tomorrow.

**Comment by skellock** [comment]
Shipping now with 1.3.  Thx again.

**Comment by oldo** [comment]
@skellock do you mean 1.1.3? Current version appears to be 1.1.4
