### ISSUE TITLE
Redux: createReactotronStoreEnhancer is not a function

### ISSUE THREAD

**Issue by fgaleano** [reactotron/reactotron#226]
I'm trying to setup up Reactotron with Redux following the instructions.

My code looks like this:

```
//Reactotron
import Reactotron from 'reactotron-react-native'  // if on mobile
import { createReactotronStoreEnhancer } from 'reactotron-redux'
const reactotronEnhancer = createReactotronStoreEnhancer(Reactotron);
```

Immediately after adding this I get the follow error:

> (0, _reactotronRedux.createReactotronStoreEnhancer) is not a function

First I realized I was using an older version of `react-native` so I upgraded to the latest. But still no cookie.

What am I missing?

**Comment by skellock** [comment]
Sorry, you caught me mid-release.  The docs are talking about the version I'm about to ship.

Change your `import { createReactotronStoreEnhancer } from 'reactotron-redux'` into `import createReactotronStoreEnhancer from 'reactotron-redux'`

**Comment by fgaleano** [comment]
@skellock Yep, that immediately worked. :) Timing, huh? 

That said, all Redux ACTION event are coming back `undefined`. I'm not using immutable.js or anything like that. Just 2 middlewares, thunk and logger, which are applied last, as per instructions.

Any quick thoughts?

Thanks!

**Comment by skellock** [comment]
And now `1.3.0` has been released.  Your code will still work though, but the new syntax (and snapshot feature) is now live.

So that's strange ya.  They shouldn't be `undefined`.  Hmm... I've only seen that with `Immutable.js` and you're not using that eh?

So you see the events then in the Reactotron App, they're just empty?

What happens if you try fetching the keys or values (Command + F) from Reactotron?  Do they come back null as well?

**Comment by fgaleano** [comment]
@skellock Manually searching for key/values does work. So it is picking up Redux's state. I'll continue to debug and see if I find anything. This is the first time I use Reactotron. Do let me know if you have any other thoughts. Thank you!

**Comment by skellock** [comment]
The actions you're dispatching.  They have a `type` right?

Is your code somewhere on github where I could take a look?  I'm very curious why this isn't working.

Also, `1.3.0` is available if you feel like upgrading... the version you have is so last hour.

**Comment by skellock** [comment]
Version 1.4 [significantly simplifies](https://github.com/reactotron/reactotron/blob/master/docs/plugin-redux.md#configuring) Redux integration.

I'd be curious to see if you have the same issue still.  Feel free to reopen.

Thanks for taking the time to file a report!
