### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by shodanuk** [reactotron/reactotron#237]
Hey,

I'm getting a "SyntaxError: Unexpected token" error when trying to import reactotron-react-js in my app. 

```
import Reactotron from 'reactotron-react-js';
```

We're using version ^1.3.0 of Reactotron with React-Boilerplate and my guess is that Webpack isn't playing nicely with reactotron-react-js but being a relatively recent convert to React & Webpack, I have no idea how to debug this.

Any help would be appreciated :)

**Comment by skellock** [comment]
Oh dear.  I wonder if I missed a babel transform on my end? My goal was to convert it to ES5.

Is this just with a fresh app on react-boilerplate?

**Comment by shodanuk** [comment]
It's not a fresh app, no. I'll set up a clean install of react-boilerplate and test it now

**Comment by shodanuk** [comment]
Ah, it works fine with a vanilla install of React-Boilerplate. Sorry, it must be some anomaly with our Webpack config

**Comment by skellock** [comment]
Oh, no worries.  Does it say which line of code is bombing?  Or is it highlightling the word `import`?

It sounds like it isnt't loading the right babel tranforms, indeed.

**Comment by shodanuk** [comment]
Ok, I think  I've worked it out. I compared our Webpack config (webpack.base.babel.js) against the current one in their repo and noticed they have an extra entry, "browser" in the "mainFields" array of the "resolve" prop. I'm not sure what I does but when I added it to our config. Reactotron sprang into life!

**Comment by skellock** [comment]
Good to know.  Thanks for the closing the loop!
