### ISSUE TITLE
Reactotron Redux Saga

### ISSUE THREAD

**Issue by rmevans9** [reactotron/reactotron#238]
Playing with the new plugin this morning and I love it. One oddity that I ran into which may not be a huge deal is forking a saga from a saga that was kicked off via a takeEvery. For example:

```
function* testSaga2() {
    yield call(aSuperMethod);
}

function* testSaga() {
    yield fork(testSaga2);
}

function* rootSaga() {
    yield [
        takeEvery('TEST_ACTION', testSaga)
    ];
}
```

In Reactotron it shows two sagas run (which is correct) but testSaga2 is named "undefined". In addition the saga that shows in Reactotron for testSaga actually shows the call to testSaga2 in its tree along with all calls that testSaga2 made.

I feel like in this example we might not want to post the stand alone testSaga2 to the timeline since the information for it is included in the saga that kicked it off.

Screen shot of a very similar set of code I tested with: 
<img width="1026" alt="screen shot 2016-11-10 at 7 12 49 am" src="https://cloud.githubusercontent.com/assets/14151327/20176305/386ac30e-a715-11e6-87ee-9f935b357437.png">

**Comment by skellock** [comment]
Gotcha.

Hmmm....

So Reactotron **should** be chopping things up at a "task" level.  In your example we have 2 tasks, so I would expect to see 2 messages.

But I do share your surprise with the 2nd message having the 1st task's info.

So tasks can be nested then... I had not thought of that at all.

I wonder if it makes sense to have an option to show/hide forked children?  Hmm I'm not sure.  What do you think?  Does it make sense in the 2nd saga to say "--- a fork happened click here to show the tree but you already saw it before in another message ---"?

Also, note to self, round the time display to the 2nd decimal place.

**Comment by rmevans9** [comment]
I personally like that the 2nd saga allows me to see what the forked saga did. This way you can see the entire effect tree. If you have to bounce between multiple messages to follow the saga that could become a headache when you have a bunch of sagas running at a time. Hiding it behind a message is fine by me as long as I can drill down into it and see the info still. 

Having the forked task (testSaga2) show as a individual message works for me but it doesn't have a name. If you fork a bunch of sagas like this you won't have any way of knowing which saga is which. Not sure if we can find a name from somewhere in that case.

Also - random thought on UI - Filtering of message types. As the timeline gains more message types it can get hard to find the ones you want.
