### ISSUE TITLE
All actions are wrapped?

### ISSUE THREAD

**Issue by Anahkiasen** [reactotron/reactotron#239]
I'm testing out the redux integration, but for some reason all my actions appear in Reactotron as wrapped in another action which makes it very hard to see at a glance what is happening:

![screen shot 2016-11-10 at 13 11 39](https://cloud.githubusercontent.com/assets/1321596/20176265/4407b38e-a747-11e6-8894-812c6b52734a.png)

Is this an option I have to configure or?

**Comment by rmevans9** [comment]
Can you show us how you are calling your actions? I ask this because I am not seeing this in my use of Reactotron. 
<img width="651" alt="screen shot 2016-11-10 at 7 16 05 am" src="https://cloud.githubusercontent.com/assets/14151327/20176392/92fb5040-a715-11e6-9f9e-d6fe03839821.png">

**Comment by Anahkiasen** [comment]
From what I've found on the internet it seems to be caused by the [react router middleware](https://github.com/acdlite/redux-router/issues/87). Solution suggested is usually to put logging middlewares before react router's but in this case I'm not sure what to change since Reactotron's only involvment is at the `createStore` level

**Comment by Anahkiasen** [comment]
Nevermind I've found what it is, it was redux devtool's composer that was adding its own wrapping to the actions:

```js
const composeEnhancers = (typeof window !== 'undefined' && window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__)
    ? window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__()
    : compose;

const store = Reactotron.createStore(reducers, initialState, composeEnhancers(middlewares));
```

If I switch it to just `compose(middlewares)` here it works

**Comment by rmevans9** [comment]
Good stuff!

**Comment by skellock** [comment]
Ahh.  You raise a good point here though.

I'm doing the same thing (in spirit) as @zalmoxisus.  We're both trying to make sure we're in front & behind the call to create store so we can maintain references.

All `Reactotron.createStore` does is inject the [right wrappers](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-redux/src/create-store.js#L11) at the right time.

A short-term work around might be to do the work of `Reactotron.createStore` manually.

```js
// first wrap your reducer to take advantage of Reactotron's state uploading/downloading
const tronducer = Reactotron.createReplacementReducer(rootReducer)

// add an additional enhancer to your list so we can monitor redux actions
const enhancers = composeEnhancers(middlewares, Reactotron.createActionTracker())

// then create your store as usual
const store = createStore(tronducer, enhancers)

// then tell Reactotron about the store so we're able to dispatch events & query the state tree from Reactotron
Reactotron.setReduxStore(store)
```

As a longer-term fix, I can probably detect `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__()` and play nicely with redux dev tools.

Caveat:  I didn't test that code, so this is pretty much me talking out of my ass right now.  I feel like it should work tho. :)

**Comment by zalmoxisus** [comment]
It's not directed related to the extension itself, but to [`redux-devtools-instrument`](https://github.com/zalmoxisus/redux-devtools-instrument), which is lifting the store and should be always the last in the compose. `window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__` takes care of it, but lately it's wrapped by Reactotron's `createStore`, which receives not the original store.

@skellock's snippet should help.
