### ISSUE TITLE
Trim the floating point precision you monster

### ISSUE THREAD

**Issue by skellock** [reactotron/reactotron#240]
![image](https://cloud.githubusercontent.com/assets/68273/20179288/6a2f32e0-a723-11e6-8eef-9a88071fa5a8.png)

**Comment by rmevans9** [comment]
Are you thinking leave a few decimals or just straight round them off? I feel like when talking in milliseconds you could just lose the decimal completely.

**Comment by skellock** [comment]
ya im totally cool with dropping precision entirely.
