### ISSUE TITLE
Filtering Messages

### ISSUE THREAD

**Issue by skellock** [reactotron/reactotron#241]
@rmevans9, @kevinvangelder, and @derekgreenberg have all asked for message filtering support.  

The use case would be:

* I'd like to just watch Saga messages or API messages.
* a UI element where i could pick a subset of all message types to show/hide

I think this is an awesome addition.

**Comment by rmevans9** [comment]
Do you have a preference of UI component for this? I might work on this over the weekend if you don't get to it first.

**Comment by skellock** [comment]
Maybe something like this?

![image](https://cloud.githubusercontent.com/assets/68273/20199720/97f308a8-a77a-11e6-9b4c-b2ce97b3312f.png)


Something simple for now?

We could copy & paste a dialog to get this up & running real quick.  

* UI state code would live in the [UiStore.js](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-app/App/Stores/UiStore.js).
* Filtering would live in [SessionStore.js](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-app/App/Stores/SessionStore.js#L40)
* Example dialog might be like [StateWatchDialog](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-app/App/Dialogs/StateWatchDialog.js)

Doesn't seem so bad, but once you see my code you might change your mind. Haha.

😍

**Comment by skellock** [comment]
Definately won't get to it until next weekend at the earliest.  We're shipping a client project next week and need to turn on the jets.  :)

**Comment by rmevans9** [comment]
Got it started. I am not sure how you are wanting the checkboxes styles so I might get it most of the way there and let you do any design touches you want to it. I will probably be able to get the checkboxes in places and the filtering working tomorrow.

https://github.com/rmevans9/reactotron/tree/FilterTimeline

**Comment by skellock** [comment]
Sweet dude!  For the checkboxes just use something like this:

https://material.io/icons/#ic_check_box
https://material.io/icons/#ic_check_box_outline_blank

Wrap 'em in an Icon [maybe like this](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-app/App/Foundation/TimelineHeader.js#L5) and use it [like this](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-app/App/Foundation/TimelineHeader.js#L69)? 

No rush.  Super appreciate any time you have to give.

**Comment by rmevans9** [comment]
And filtering is working. 

Outstanding items:

- Make the dialog look....good
- Put all of the command types in the dialog
- Cleanup some of the code
- Have someone that actually knows MobX review my use of MobX (first time use...woo!)

**Comment by rmevans9** [comment]
PR opened to show the changes thus far and track future changes as this gets completed. #245
