### ISSUE TITLE
How do I display the action name in either OS X app or cli?

### ISSUE THREAD

**Issue by jbenesch** [reactotron/reactotron#249]
In theOS X app, I see: `ACTION    PERFORM_ACTION`, when I click on the row, my action (FSA) is buried in an action object

```
{
  type:PERFORM_ACTION,
  action:{
    type:API_REQUEST
    payload: { ... }
  },
  timestamp:1478898596496
}
```

And in the terminal, I only see: `PERFORM_ACTION  105ms`.

While I love both the interfaces, not being able to actually see the action name/info makes it cumbersome to try and use. This also has the unfortunate side effect of when I want to trigger an action from the UI, I have to edit the action json shape every time extracting my action out of the perform_action, action, object...  I'm creating my redux store like so:

```
import { applyMiddleware, compose } from 'redux';
import thunk from 'redux-thunk';
import createLogger from 'redux-logger';
import rootReducer from 'reducers';
import Reactotron from 'reactotron-react-js';

const logger = createLogger({
  duration: true,
  collapsed: true,
});

const middleware = compose(
  applyMiddleware(thunk, logger),
  window.devToolsExtension ? window.devToolsExtension() : f => f
);

export default function configureStore() {
  const store = Reactotron.createStore(rootReducer, middleware);
  return store;
}
```

What am I doing wrong? Any pointers would be greatly appreciated! Thanks for your awesome open source work!

**Comment by skellock** [comment]
Currently there's a collision between redux dev tools and reactotron.

[Here's a short term workaround](https://github.com/reactotron/reactotron/issues/239#issuecomment-259685156).

**Comment by jbenesch** [comment]
I swore I looked through the issues first... sigh. Thanks! sorry for having to repeat yourself!

**Comment by skellock** [comment]
No worries.  I'll figure out an easier way to make them work together.
