### ISSUE TITLE
Redux Saga 0.13.0 + Reactotron Saga Monitor = SADNESS

### ISSUE THREAD

**Issue by rmevans9** [reactotron/reactotron#259]
It looks like 0.13.0 added a new call on the saga monitor that isn't being passed in by the reactotron saga monitor. We end up with:

`sagaMonitor.actionDispatched is not a function`

from Redux Sagas release notes:

> added actionDispatched trigger to the monitor contract. We need this in order to figure out saga/take effects that reacted to a given action. Also added a silent flag SAGA_ACTION (non enumerable property) added to distinguish actions dispatched by sagas from others.

A quick fix might be to just pass a noop function until it is figured out if this new monitor function could help

**Comment by skellock** [comment]
Cheers.  I wonder if they'd be open to making each function of the sagaMonitor optional?

Lemme get your PR patched in & released.

Thanks.
