### ISSUE TITLE
Reactotron Saga Monitor - Saga Names

### ISSUE THREAD

**Issue by rmevans9** [reactotron/reactotron#261]
In certain setups sagas end up with the description of 'undefined'. I will work on providing a simple example of the setup I am seeing but I wanted to get this out here so I don't forget about it.

Possible thoughts:

- Beef up how the description is generated to try and find a name.
- Provide a way for a saga to declare its own name (this might be something that is hard since the monitor is just watching what redux saga is doing)

**Comment by rmevans9** [comment]
Side note: In my production app when it gets into the task resolved method effectInfo actually has a description that I would like to see output to reactotron as it is the name of method that is running the saga.

**Comment by skellock** [comment]
I've seen what you're talking about.

I think I've seen it happen when a forked saga ends and it's parent is not an `ITERATOR` (ie takeLatest). 

Adding some [extra `else` conditions](https://github.com/reactotron/reactotron/blob/master/packages/reactotron-redux-saga/src/saga-monitor.js#L76) might be the answer:

**Comment by skellock** [comment]
Is this the same as #238 ?  I think it is.

I'm not sure if we can provide a name.  I think that's entirely `redux-saga`.  I noticed there was a `label` property attached to their `effectInfo` object, but that's used for the `RACE` effect to determine winners/losers.

**Comment by rmevans9** [comment]
#238 was created because of the multiple sagas but I guess I did mention the undefined saga names as well. I would be open to closing this in favor of that one if you want.

I am wondering if we can just use the description off the `effectInfo` if we end up undefined right before we ship the data to reactotron. In my tests description usually has something close enough that it would tell me what saga it is at a quick glance.

**Comment by skellock** [comment]
That's cool, let's keep going on this one.

So ya, I think you're probably right.  I'll give that a go and see what it looks like.

**Comment by rmevans9** [comment]
I did a quick change to just default out to `effectInfo.description` on the app I am running into the undefined saga names and it is working really well so far. If you like I can throw a PR to do that out there.

**Comment by skellock** [comment]
Sounds good.

I'm about to push a build out today, so that'd be cool if we can include that as well.

Just a heads up, I pushed some stuff into master but since it's not released yet, it'll trip up the demos.

At the root of the project if you run `yarn run bootstrap`.  Until i get to a script that will clean up everything for devs, i recommend

```sh
cd packages/demo-react-js
rm -rf node_modules
yarn
cd ../..
cd packages/demo-react-native
rm -rf node_modules
yarn
cd ../../
yarn run bootstrap
cd packages/demo-reacto-native
./copy_internal-deps
cd ../..
```

Ugh, that was painful even to type.

**Comment by rmevans9** [comment]
Sorry, I haven't had a chance to get this fix out there. I will work on this tonight or tomorrow morning and have a PR out for it.

**Comment by skellock** [comment]
No rush man.  I'll take a quick look at it tonight when I push the next version.

**Comment by rmevans9** [comment]
#267 opened

**Comment by skellock** [comment]
Cheers.  Shipping in 1.5.2.
