### ISSUE TITLE
Windows binary not included in 1.5.0 release

### ISSUE THREAD

**Issue by tsemerad** [reactotron/reactotron#263]
I just noticed that a Windows binary wasn't included in the 1.5.0 release. I'm assuming that was just a mistake?

**Comment by skellock** [comment]
Sorry about that.  I've yet to automate that part.

Appreciate the heads up!

👍

**Comment by aarongifford** [comment]
Thanks for the fix :)

**Comment by skellock** [comment]
No prob.  I just probably put an issue together with what I think is left for windows.  It's basically packaging... so an icon & an NSIS installer.  Wow, now that I say it out loud, there's not a lot left.
