### ISSUE TITLE
React-native socket.io-client require problem

### ISSUE THREAD

**Issue by ricardofbarros** [reactotron/reactotron#279]
Currently after a fresh install I get this `Requiring unknown module "socket.io-client/socket.io". I traced it back to this [PR](https://github.com/socketio/socket.io-client/pull/1025)

They changed the path of the minified file. I will be pushing a PR shortly addressing this changes.

**Comment by skellock** [comment]
Thank you.  I had a lot of issues getting this behaving on both React JS and React Native.  I hadn't realized it was busted.

**Comment by skellock** [comment]
Thanks again.  This is now shipping in `1.5.3`.  Cheers man!
