### ISSUE TITLE
When I launch the app it is empty

### ISSUE THREAD

**Issue by ericvera** [reactotron/reactotron#287]
I tried the steps [for the quick start react js](https://github.com/reactotron/reactotron/blob/master/docs/quick-start-react-js.md) with the create-react-app option and I see nothing. Not even the connect event. `npm start` launches the site in `http://localhost:3000` so I tried changing the `ReactotronConfig.js` file to

    import Reactotron from 'reactotron-react-js';
    
    Reactotron
      .configure({port:3000}) // we can use plugins here -- more on this later
      .connect(); // let's connect!

Also tried passing the same argument to `.connect();` with no success.

When looking at the Chrome console I see the following after a few seconds. 

    WebSocket connection to 'ws://localhost:3000/socket.io/?EIO=3&transport=websocket' failed:       WebSocket is closed before the connection is established.

It seems to work for others so let me know if there is any info I can get to help with troubleshooting.

**Comment by skellock** [comment]
If you delete the `{port :3000}`, it'll use port `9090`.  Which is where the App is listening.

Have you tried that?
There isn't any firewalls in play here?  
Nothing else is already listening on that port 9090 is it?
Is this on the Mac?
And it you mentioned that it's just plain `http` right?
Can you verify you're running `1.5.0` of the App (in the Reactotron About menu)?
Can you verify you're running `1.5.3` of `reactotron-react-js` (in your package.json)
Also, restart the App (lame suggestion, I know)?

Thanks,

Sorry for the problems.

**Comment by ericvera** [comment]
I tried removing the port before and it was not working, but now all of the sudden everything is working. I wonder if I had something else in the code causing other issues. Thanks for the crazy quick response and the help! Looking forward to trying this out.

**Comment by skellock** [comment]
Sweet!

**Comment by atinder** [comment]
In case anyone faces this. Had a similar issue. Fixed it by upgrading reactoron mac app.
