### ISSUE TITLE
[reactotron-react-native] createStore is not a function

### ISSUE THREAD

**Issue by joncursi** [reactotron/reactotron#289]
I'm running into this error while setting up Reactotron with Redux per the installation guide.

Redux config:

```jsx
import { applyMiddleware, compose } from 'redux';
import createLogger from 'redux-logger';
import Reactotron from 'reactotron-react-native';

import { reducer } from '../reducers';

const middleware = [
  createLogger(),
];

const enhancers = compose(
  applyMiddleware(...middleware)
);

export const store = Reactotron.createStore( // error happens here, createStore is undefined (?)
  reducer,
  enhancers,
);
```

Reactotron config:

```jsx
import Reactotron, { trackGlobalErrors } from 'reactotron-react-native';
import { reactotronRedux } from 'reactotron-redux';

if (__DEV__) {
  Reactotron
    .configure()
    .use(reactotronRedux())
    .use(trackGlobalErrors())
    .connect();
}

```

Package versions:

```
    "reactotron-react-native": "^1.5.3",
    "reactotron-redux": "^1.5.3",
```

Error:

![screen shot 2016-12-01 at 8 17 02 am](https://cloud.githubusercontent.com/assets/4974609/20795323/98946f02-b79e-11e6-8c85-1bbb1d522a4d.png)

I can't tell what's wrong. Any ideas?

**Comment by rmevans9** [comment]
Can you make sure that the ReactotronConfig is getting called before your redux store setup?

**Comment by joncursi** [comment]
Ah, silly mistake, thank you! I was importing my Reactotron configuration in a custom location rather than on Line 1 as the Readme asks.

**Comment by rmevans9** [comment]
No worries. Also note that since in your redux setup you are unconditionally using createStore off Reactotron a production build will actually fail. Make sure to conditionally use the redux provided createStore when not in dev

**Comment by joncursi** [comment]
👍 thanks for the tip!
