### ISSUE TITLE
unknown named module socket.io-client/socket.io

### ISSUE THREAD

**Issue by raviteja83** [reactotron/reactotron#293]
socket.io and socket.io-client are both installed but still getting the error with **RN-0.33.1** and **reactotron 0.9.0**

**Comment by pgom** [comment]
I'm getting the same error.

**Comment by rmevans9** [comment]
Reactotron 0.9.0 is fairly old... can you guys update to the latest version and try again?

**Comment by skellock** [comment]
@rmevans9  is right.  When we went to `1.0.0` we switched up the interface a bit.  You'll want to use `reactotron-react-native`.

There's a [quick start guide](https://github.com/reactotron/reactotron/blob/master/docs/quick-start-react-native.md) available as well as a [demo app](https://github.com/reactotron/reactotron/tree/master/packages/demo-react-native) you can use get get going.

I'll be writing a blog post shortly on all this stuff too, which will set a nicer stage for getting started.

Sorry for the bumps!

**Comment by Balamir** [comment]
I'm getting this error with **RN 0.53.0** and **reactotron 1.1.4**

**Comment by skellock** [comment]
Ensure all your reactotron libs are in the 1.x branch.

**Comment by hemraj-s** [comment]
Facing same issue. Installed it in an existing application and get the same error.

**Comment by skellock** [comment]
Can you open a new issue and paste some details?
