### ISSUE TITLE
reactotron-redux: b.__iterate is not a function

### ISSUE THREAD

**Issue by joncursi** [reactotron/reactotron#297]
When I plug in Reactotron to my Redux-enabled app via `store = Reactotron.createStore(...)`, I started seeing this error pop up after dispatching several of my app's actions:

![screen shot 2016-12-07 at 7 10 25 am](https://cloud.githubusercontent.com/assets/4974609/20967321/dd43a6d8-bc4c-11e6-8c6b-00d3cc04e432.png)

Only certain payloads seem to cause it. Here are example payloads that don't work:
* ImmutableJS List

Removing Reactotron from the equation eliminates these errors. I googled around a little bit and couldn't find any hits for this type of error, so it looks like it's isolated to Reactotron. Any thoughts on why this is happening, and / or what this means? Thanks!

**Comment by rmevans9** [comment]
Looks like some of the work to serialize functions to a basic string for display in Reactotron is causing some issues for you. Is there anyway you could find out what the payload is when this error is thrown?

**Comment by joncursi** [comment]
Thanks for your quick reply - yep, here's an example: an ImmutableJS List as the payload. Here I am running a `console.log()` statement on the payload immediately before the action is dispatched. You can see that it's a List and when the action is dispatched with the List as a payload, attempting to set the List on the global state runs into this error.

<img width="685" alt="screen shot 2016-12-07 at 7 21 20 am" src="https://cloud.githubusercontent.com/assets/4974609/20967522/ed445b08-bc4d-11e6-9c0a-f4961e367373.png">

**Comment by rmevans9** [comment]
ah it might be that ImmutableJS isn't really supported (yet). If I have some time later I will setup a test app with ImmutableJS and see if this is something that is easily overcome.

**Comment by joncursi** [comment]
Thanks! I noticed that when I dispatch numbers and strings everything works great, but yeah, it seems anything wrapped in ImmutableJS (Lists, Maps, etc.) will cause trouble.

**Comment by rmevans9** [comment]
Good to know. I will report back once I have some time to give this a go and see what is going on.

**Comment by skellock** [comment]
I'd love to have ImmutableJS support.  I don't personally use it (I use `seamless-immutable`), but I think most people do because Facebook recommends it.

I'll close this one in favour of #242.  I appreciate the heads up!
