### ISSUE TITLE
Register actionCreators for use on the server

### ISSUE THREAD

**Issue by andrewvy** [reactotron/reactotron#43]
An interesting idea is being able to register names of Action Creators on the app and allowing the server to interface with them.

Something like the `client` sending the available actionCreators on connect, which is just an array of keys sent to the server.

When the server wants to use an action creator, it can send an action along the lines of..

```js
{
  type: 'actionCreator',
  name: 'addTodo',
  arguments: [{ name: "New todo" }]
}
```

Which the client can then execute and dispatch. :)

Reminds me of JSON RPC. :stuck_out_tongue:

**Comment by skellock** [comment]
Well, we have the ability to `dispatch` already.  It'd be just a matter of sending the list of action creators to the client to arm them.

How would we deal with parameters though?  And types?

**Comment by andrewvy** [comment]
Yeah.. this does open a can of worms. I'm honestly not sure, you could leave it up to the user to know how to use their action creators. But that definitely leads to executing the action creator with wrong params, causing a crash on the client. :thought_balloon:

**Comment by skellock** [comment]
Well, with a store enhancer, we could track all dispatched actions, and analyze what the the types are of the arguments, but then you'd have to dispatch an action to "qualify", which doesn't sound awesome at all.

Another option could be ...

When the server starts up, it could open up your action creator files and analyze then with something like https://github.com/facebook/jscodeshift .   

Now that seems crazy...  ⚠️ 

So far, i really haven't needed to dispatch actions from the server to the client... but we're just getting started here.

**Comment by skellock** [comment]
I can't really think of a good way of adding this without a lot of effort from the calling app.  I'd hate to impose a structure on their app either.  I'm going to close this.  Thanks dude!
