### ISSUE TITLE
Requiring unknown module "socket.io-client/socket.io"

### ISSUE THREAD

**Issue by maraujop** [reactotron/reactotron#48]
Hi Steve,

First, thanks for releasing such a wonderful tool. I decided to give it a go in the project we are building. I upgrade to version RN 23 first without issues, then I added to `App.js` which is used by both platform indexes:

```
import Reactotron from 'reactotron'

Reactotron.connect()
Reactotron.connect({enabled: __DEV__})
```

This goes before configuring the redux store. However I'm getting this red screen:

![captura de pantalla 2016-04-26 a las 11 08 37](https://cloud.githubusercontent.com/assets/252257/14812909/9757d468-0b9f-11e6-973c-2b1d9d861282.png)

The moment I remove those 3 previous lines everything works again.

Thanks, cheers
Miguel

**Comment by skellock** [comment]
Hi Miguel,

How did you install?  `npm i reactotron --save-dev`?  

It sounds like the dependency on socket.io failed to be installed properly.

Looks like you're on Android too.  Try another `react-native run-android`.

One other thing, you've got two `connect()` calls.  You only need one.  Try nuking the first one.

Lemme know how it goes.

**Comment by maraujop** [comment]
Hi Steve,

That's right, I installed it with `--save-dev` argument, If I list `node_modules` directory inside reactotron I get:

```
blessed    gemoji     ramda      ramdasauce strman
```

Nothing about `socket.io`, which I'm guessing smells. 

Yes, I'm in Android too, I've recompiled several times, but it's not fixing the issue. I removed the first connect, but that didn't help either.

Thanks for your super fast answer!
Miguel

**Comment by skellock** [comment]
Woah.  ya, that's not right.

https://github.com/skellock/reactotron/blob/master/package.json#L41

Hmm... 

What happens if you type `npm install socket.io --save` from your project?  can you install it explicitly?

**Comment by maraujop** [comment]
I just tried to install `socket.io` with your command and it did work:

```
─$ npm install socket.io --save                                                                                                                                                                                            127 ↵
socket.io@1.4.5 node_modules/socket.io
├── has-binary@0.1.7 (isarray@0.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── socket.io-parser@2.2.6 (isarray@0.0.1, json3@3.3.2, component-emitter@1.1.2, benchmark@1.0.0)
├── socket.io-adapter@0.4.0 (socket.io-parser@2.2.2)
├── engine.io@1.6.8 (base64id@0.1.0, ws@1.0.1, accepts@1.1.4, engine.io-parser@1.2.4)
└── socket.io-client@1.4.5 (to-array@0.1.4, indexof@0.0.1, component-bind@1.0.0, component-emitter@1.2.0, backo2@1.0.2, object-component@0.0.3, parseuri@0.0.4, engine.io-client@1.6.8)
```

I'm surprised too, if you have it listed in your `package.json` it should be installed, I'm gonna check if I can upgrade my npm.

**Comment by skellock** [comment]
Here's my setup (osx 10.11.4 & brew-based node)

![image](https://cloud.githubusercontent.com/assets/68273/14818030/c3bf2cde-0b88-11e6-9f04-6c604622a7f2.png)

**Comment by avioli** [comment]
Well... `socket.io-client` is a dependency for `socket.io`. Prior `npm 3`, modules' dependencies were not available to all other modules and sub-modules. Not even the main project!

**Comment by maraujop** [comment]
I use nvm, and I've installed node v5.10.1 as you have, also with npm 3.8.6. I delete my `node_modules` and reinstall everything. Apparently since version 3 of npm dependencies are flatten in `node_modules` directory. However after doing so, I hit random packager bugs reported in RN. Specially this one:

![captura de pantalla 2016-04-27 a las 10 42 31](https://cloud.githubusercontent.com/assets/252257/14847449/f730c06a-0c68-11e6-943a-36bd120ef11e.png)

![captura de pantalla 2016-04-27 a las 10 42 25](https://cloud.githubusercontent.com/assets/252257/14847455/f9eb10c6-0c68-11e6-8bdd-a6889eef7309.png)

Unable to find `prelude_dev.js` file, although it's there. The transformation process of the packager hangs there without finishing, similar to https://github.com/facebook/react-native/issues/2949

When I use npm **2.15.3** with node **v4.1.1** the packager is able to transform my project but I end up with the socket.io-client/socket.io unknown module.

To be honest, I'm not sure what can I do to upgrade versions of node and npm without having issues. But I now believe that reactotron needs npm version 3 or newer.

Miguel

**Comment by skellock** [comment]
Thanks guys.  For npm 2.x, I wonder if it is simply required to add dependencies for socket.io's dependencies too? Seems odd.  I'll look at other packages for socket.io and see what they do.

@maraujop - what happens if you remove reactotron from the equation? Does it work?  Is it something in this module that is triggering this problem?

**Comment by skellock** [comment]
I just pushed `0.6.1` which now supports Node 4.x and npm 2.x.   

Would you mind giving that a go @maraujop ?

Thank you kindly!

**Comment by maraujop** [comment]
Thanks Steve,

I can confirm the bug fix did work. I've just installed `0.6.1` with npm 2 and it no longer prompts a red screen, great! I'm so excited to see reactotron working :)

About when I use npm 3, I believe in that case it is another module the one that triggers the issue, however it will be hard to find, like find a needle in haystack.

I'm closing the issue and thanks for your great support again,
Miguel

**Comment by maraujop** [comment]
Ok,

Today I discovered that reactotron 0.6.1 binary currently needs socket.io installed standalone apart to work. I happened to have it installed from one of my several tests and I didn't realize it until now. It doesn't affect the rest of the library, only running the CLI.

```
─$ node_modules/.bin/reactotron
module.js:341
    throw err;
    ^

Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/map/ticketea/geminis/node_modules/reactotron/bin/reactotron.js:13:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
````

Maybe this helps, polishing the missing pieces, although I can still use it easily, just installing socket.io apart.

**Comment by skellock** [comment]
I can't seem to reproduce this.  I've tried on node 4.x, 5.x, and 6.x on a fresh project.

I do have `socket.io` and `socket.io-client` listed as dependencies, but only as of 0.6.1.  Can you:

`npm rm -D reactotron`
`npm i -D reactotron`

Does that work?

**Comment by maraujop** [comment]
Thanks Steve and sorry for the late answer, I've had health issues lately and I've out of the internet for a while.

You were right it does work.

Cheers,
Miguel

**Comment by skellock** [comment]
On behalf of the citizens of the Internet, welcome back!  👋

**Comment by vjpr** [comment]
@skellock I have the same issue with `socket.io-client` and `ramda` with npm@2.

E.g.

```
Module not found: Error: Cannot resolve module 'ramda' in /app/node_modules/reactotron-react-js/dist
```

**Comment by skellock** [comment]
i think with npm 2, the nested dependencies are quite found properly.  :(

I'd love to support npm 2, but I'm afraid I can't quite crack the cadury secret.

I'll make a note about the npm 3 requirement for now.  Sorry!

**Comment by vjpr** [comment]
> I'll make a note about the npm 3 requirement for now. Sorry!

The package spec is broken. The fix is simple. Add `ramda` and `socket.io-client` to `package.json`.

Relying on a transitive dependency is a bad idea - this transitive dependency may disappear and break your package. E.g. what happens if `socket.io` doesn't depend on `socket.io-client` anymore.

**Comment by skellock** [comment]
Thank you!  I'll patch this up!  Just travelling at the moment.
