### ISSUE TITLE
Add ApiLog support for superagent

### ISSUE THREAD

**Issue by DanielMSchmidt** [reactotron/reactotron#54]
Hi there,

First of all thanks for this great tool! I was wondering if there would be any interest in adding support for [superagent](https://www.npmjs.com/package/superagent), I would love to implement this. I guess I would only have to [change the APILog command](https://github.com/skellock/reactotron/blob/master/server/commands/api/apiLog.js). Is there any interest from your side in adding such a feature?

**Comment by skellock** [comment]
Hello @DanielMSchmidt!  

I'd love to support more than 1 type of API.  #26 is related to this one too.  

The API support that went into reactotron was a bit short sighted.  My bad.

I think the way out of this is to move much of that logic to the client.  So we only pass data to the server in a format that works for every networking api.  

```
{
  url: 'https://api.awesome.com/v2/things',
  headers: {},
  status: 200,
  duration: 155,
  data: {}
}
```

Something along the lines of that.

I've got a few days of vacation left, but I'll add this to my list of things to knock out!  Or if you're feeling up for it, I'd totally support you replacing the mess I made.  :)

**Comment by DanielMSchmidt** [comment]
Okay, have a nice vacation! If you would build the server side endpoint I would go ahead and build the superagent specific parts, maybe as an own module to be more flexible in the next versions.

**Comment by skellock** [comment]
We now use `json` as in interface between the client & server, so it's now possible to write a `superagent` if you'd like.  Probably just need to hook the `on('end')` callback or something.

Here's the interface:
https://github.com/reactotron/reactotron/tree/next/packages/reactotron-core-client#apiresponse

Here's an example of what it might look like:
https://github.com/reactotron/reactotron/blob/next/packages/reactotron-apisauce/src/index.js

Hasn't been released just yet.  Hopefully soon.

**Comment by DanielMSchmidt** [comment]
Awesome, I will have a look at it soon
