### ISSUE TITLE
Support for inspecting redux actions

### ISSUE THREAD

**Issue by deoqc** [reactotron/reactotron#56]
I believe that inspecting the dispatched actions is a must. Is there a plan to support it or is it out-of-scope for this project?

**Comment by skellock** [comment]
Agreed 100%.  It is in, but hidden because it sometimes dispatched actions can contain way too much info.  

I'll revisit this to see if I make it an option to toggle.

Thanks for taking the time to log an issue.

**Comment by skellock** [comment]
This will be in the Electron version.  I'll still look into the CLI, but it'll be after 1.0.  Thanks!
