### ISSUE TITLE
Support for re-frame (ClojureScript)

### ISSUE THREAD

**Issue by vikeri** [reactotron/reactotron#57]
This seems quite excellent. And fortunately it would conceptually work very well with the popular ClojureScript frontend framework [re-frame](https://github.com/Day8/re-frame) that is very similar to Redux but implemented in ClojureScript.

Would it be possible to open this up for other uni-directional data implementations than Redux? Maybe provide some kind of API?

**Comment by skellock** [comment]
Heyo!

This is very possible.  Actually this is very similar in spirit to the solution proposed to #54.

I'll take a look at re-frame to see what's up. 

Do you think this would require a ClojureScript client?  Or can you call JS directly?   As you can tell, I know nothing about it.

**Comment by vikeri** [comment]
Great to hear! ClojureScript can call JavaScript directly so no need to implement it in ClojureScript. Being a functional language it is preferable to interact with functions rather than objects though.

**Comment by skellock** [comment]
So for 1.0, we'll have a JSON interface between the client and server.  This paves the way for some custom stuff like what you're looking for.

https://github.com/reactotron/reactotron/tree/next/packages/reactotron-core-client#messages

Coming soon.
