### ISSUE TITLE
Slow Down and 100% CPU Usage

### ISSUE THREAD

**Issue by skellock** [reactotron/reactotron#62]
One thing I've noticed is that Reactotron gets slow over time.  Eventually it pins the CPU at 100%.

I think this is websockets related (or how I handle them).

It seems to show up sooner the more I reload & hot reload my React Native apps.

:(

**Comment by skellock** [comment]
It's running significantly faster on the Electron version.  Still on my radar for the CLI.

**Comment by skellock** [comment]
Closing this out... much much better now in the `next` branch.

**Comment by maluramichael** [comment]
Is it possible that there are to many entries in the event timeline after a while?

**Comment by skellock** [comment]
Possibly.

I do have (what I believe to be) a 100 message cap though.

https://github.com/reactotron/reactotron/blob/master/packages/reactotron-core-server/src/commands.js#L49
